# Generated by Django 4.1 on 2023-03-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_docteur_parcours_docteur_specialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docteur',
            name='parcours',
        ),
        migrations.RemoveField(
            model_name='docteur',
            name='specialite',
        ),
    ]
