# Generated by Django 4.1 on 2023-04-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_docteur_parcours_remove_docteur_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteur',
            name='contact',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docteur',
            name='parcours',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docteur',
            name='specialite',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
